# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("users.proto", :syntax => :proto3) do
    add_message "helloworld.GetUserRequest" do
      optional :id, :int32, 1
    end
    add_message "helloworld.GetUserReply" do
      optional :email, :string, 1
      optional :name, :string, 2
      optional :id, :int32, 3
    end
  end
end

module Helloworld
  GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.GetUserRequest").msgclass
  GetUserReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.GetUserReply").msgclass
end
