# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: users.proto for package 'helloworld'

require 'grpc'
require_relative './users_pb'

module Helloworld
  module Users
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.Users'

      rpc :GetUserById, ::Helloworld::GetUserRequest, ::Helloworld::GetUserReply
    end

    Stub = Service.rpc_stub_class
  end
end
